name: Release Obsidian plugin new

on:
  push:
    tags:
      - "*"
env:
  PLUGIN_NAME: obsidian-vscode-editor # Change this to the name of your plugin-id folder

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: Zip plugin
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        mkdir ${{ env.PLUGIN_NAME }}
        cp  main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
        zip -r ${{ env.PLUGIN_NAME }}-"$tag".zip ${{ env.PLUGIN_NAME }}

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF#refs/tags/}"

        gh release create "$tag" \
          --title="$tag" \
          --draft \
          main.js manifest.json styles.css obsidian-vscode-editor-"$tag".zip
